# Nome del progetto
name: cinegeek

# Breve descrizione del progetto
description: "CineGeek - App context-aware per cinema e recensioni film"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^12.0.0
  sensors_plus: ^6.0.1
  flutter_local_notifications: ^17.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  provider: ^6.1.2
  circle_nav_bar: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  cupertino_native: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_con_sfondo.png
    - assets/images/logo_intero.png
    - assets/images/solo_logo.png
    - assets/images/solo_testo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
